Changed part concerning older versions of Java
3AP-AG/dotfiles pull request #2
Opened 2019-10-08 07:58 UTC by zlatkela

Installing java8 is not possible with cask (java8 cask is no longer available). Instead, we need to use adoptopenjdk8
See this for details: https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac

2019-10-08 11:50 UTC, primaproxima commented
@gabac We were unable to install java 8 with this setup, so Milos adapted to the working solution.

2019-10-11 06:59 UTC, gabac commented
Please refer from installing java8 and switch to java11

2019-10-11 07:07 UTC, gabac requested changes
Please use Java 11

2019-10-13 07:55 UTC, gabac commented
I think we actually should improve the workflow here, so that we can easly switch between Java versions

https://stackoverflow.com/questions/52524112/how-do-i-install-java-on-mac-osx-allowing-version-switching

cc
@robertblust

2019-11-19 09:43 UTC, primaproxima commented
I will remove the java related command and adapt the Java page in the CTO space.

2019-11-19 09:46 UTC, mnembrini commented
I use https://sdkman.io/ to manage JVM version and am very happy with it

2019-11-19 11:55 UTC, gabac commented
I still want Java to be installed through the dotfiles. That is **the** reason for dotfiles

2019-11-19 12:03 UTC, primaproxima commented
@gabac Then we need to do 2 things:
1. revert my PR that was merged today - I can do that
1. do something with this PR(?)

2019-11-19 12:06 UTC, gabac commented
1) We need to decide how we want to provide java installations. This can be opinionated e.g. we say lets do this with `sdkman`

2) Create PR for this

2019-11-19 15:10 UTC, gabac commented
@primaproxima Will you provide a PR for this?

2019-11-22 10:41 UTC, primaproxima commented
@gabac yes, I will :)

2019-11-25 16:05 UTC, primaproxima commented
Seems this didn't work today on @nevena3ap's machine.

2019-11-25 16:40 UTC, gabac commented
> Seems this didn't work today on @nevena3ap's machine.
What did not work, what was the error message?

2019-11-25 16:44 UTC, primaproxima commented
```
failed: [localhost] (item=adoptopenjdk11) => {"ansible_loop_var": "item", "changed": false, "item": "adoptopenjdk11", "msg": "Error: Cask 'adoptopenjdk11' is unavailable: No Cask with this name exists."}
```

She installed it with the help of @zlatkela via:
```
brew cask install homebrew/cask-versions/java11
```

2019-11-25 16:59 UTC, zlatkela commented
Yes, my bad, sorry about that. I saw it at https://github.com/AdoptOpenJDK/homebrew-openjdk and took it for granted and at my machine installation was probably skipped, because I already had it installed when this was changed.

2019-11-25 17:00 UTC, primaproxima commented
> Yes, my bad, sorry about that. I saw it at https://github.com/AdoptOpenJDK/homebrew-openjdk and took it for granted and at my machine installation was probably skipped, because I already had it installed when this was changed.

No worries, we will handle it with a new PR with sdkman. 👍

2019-12-10 08:37 UTC, closed without merging